/*******************************************************************************
 * locals.js - Translation rules for Hugging Face 中文化增强脚本.
 *
 * Add missing translations here first. Keep product names, model names, dataset
 * names, usernames, and generated content untranslated unless they are fixed UI.
 ******************************************************************************/
var I18N = {};

I18N.conf = {
  characterDataPages: ["welcome", "docs", "learn", "models", "datasets", "spaces", "settings", "public"],
  ignoreSelectors: {
    "*": [
      "pre",
      "code",
      "textarea",
      ".markdown-body",
      ".model-card-content",
      ".blog-content",
      ".prose-doc",
      ".prose-card",
      ".hf-sanitized",
      "relative-time",
      '[data-testid="breadcrumb"]',
      "[data-repo]",
      "[data-user]",
    ],
    welcome: [],
    models: [],
    datasets: [],
    spaces: [],
    docs: [],
    learn: [],
    settings: [],
    public: [],
  },
};

I18N["zh-CN"] = {
  public: {
    static: {
      Models: "模型",
      Datasets: "数据集",
      Spaces: "应用空间",
      Space: "应用空间",
      Docs: "文档",
      Pricing: "定价",
      Enterprise: "企业版",
      Tasks: "任务",
      Collections: "收藏集",
      Blog: "博客",
      Posts: "帖子",
      Papers: "论文",
      Organizations: "组织",
      "Log In": "登录",
      "Sign Up": "注册",
      Settings: "设置",
      Profile: "个人资料",
      New: "新建",
      Search: "搜索",
      Upload: "上传",
      Cancel: "取消",
      Save: "保存",
      Submit: "提交",
      Continue: "继续",
      Back: "返回",
      Next: "下一步",
      Done: "完成",
      Edit: "编辑",
      Delete: "删除",
      Create: "创建",
      Learn: "学习",
      Forum: "论坛",
      "Getting Started": "开始使用",
      "Get started": "开始使用",
      "Read the documentation": "阅读文档",
      "Create new Space": "创建新应用空间",
      "Ask HuggingChat": "向 HuggingChat 提问",
      "Data Studio": "数据工作室",
      "Inference Endpoints": "推理端点",
      "Inference Providers": "推理供应商",
      "Daily Papers": "每日论文",
      "The AI community building the future.": "构建未来的 AI 社区。",
      "Team & Enterprise": "团队与企业版",
      "Hugging Face PRO": "Hugging Face PRO",
      "Enterprise Support": "企业支持",
      "Storage Buckets": "存储桶",
      "Create a new model": "创建新模型",
      "Create a new dataset": "创建新数据集",
      "Create a new Space": "创建新应用空间",
      "New model name": "新模型名称",
      "New dataset name": "新数据集名称",
      "New Space name": "新应用空间名称",
      "Owner": "所有者",
      "Visibility": "可见性",
      "Public": "公开",
      "Private": "私有",
      "License": "许可证",
      "Hardware": "硬件",
      "SDK": "SDK",
      "Files": "文件",
      "Community": "社区",
      "Settings": "设置",
      "Deploy": "部署",
      "Downloads": "下载量",
      "Likes": "点赞",
      "Updated": "已更新",
      "Created": "已创建",
      "Sort by": "排序方式",
      "Filter by": "筛选条件",
      "Apply filters": "应用筛选",
      "Reset filters": "重置筛选",
      "No results found": "没有找到结果",
      "Try another search": "换个关键词试试",
      "System theme": "系统主题",
      "Light theme": "浅色主题",
      "Dark theme": "深色主题",
      "Terms of service": "服务条款",
      "Privacy": "隐私政策",
      "About": "关于",
      "Careers": "招聘",
      "Company": "公司",
      "Resources": "资源",
      "Social": "社交",
      "Changelog": "更新日志",
      "Service Status": "服务状态",
      Documentation: "文档",
      "Search documentation": "搜索文档",
      "Search docs": "搜索文档",
      "Search the Hub": "搜索 Hub",
      "View all docs": "查看全部文档",
    },
    regexp: [
      [/^Updated (.+) ago$/, "$1 前更新"],
      [/^Created (.+) ago$/, "$1 前创建"],
      [/^([0-9,.]+) likes?$/, "$1 个点赞"],
      [/^([0-9,.]+) downloads?$/, "$1 次下载"],
      [/^Browse ([0-9,.]+[kKmM+]*) models$/, "浏览 $1 个模型"],
      [/^Browse ([0-9,.]+[kKmM+]*) datasets$/, "浏览 $1 个数据集"],
      [/^Browse ([0-9,.]+[kKmM+]*) applications$/, "浏览 $1 个应用"],
      [/^Showing ([0-9,.]+) results?$/, "显示 $1 个结果"],
      [/^Search (models|datasets|spaces)$/, "搜索$1"],
    ],
    selector: [
      ["a[href='/models']", "模型"],
      ["a[href='/datasets']", "数据集"],
      ["a[href='/spaces']", "应用空间"],
      ["a[href='/docs']", "文档"],
      ["a[href='/pricing']", "定价"],
      ["a[href='/enterprise']", "企业版"],
      ["a[href='/blog']", "博客"],
      ["a[href='/posts']", "帖子"],
      ["a[href='/papers']", "每日论文"],
      ["a[href='/login']", "登录"],
      ["a[href='/signup']", "注册"],
      ["footer a[href='/models']", "模型"],
      ["footer a[href='/datasets']", "数据集"],
      ["footer a[href='/spaces']", "应用空间"],
      ["footer a[href='/pricing']", "定价"],
      ["footer a[href='/docs']", "文档"],
      ["footer a[href='/privacy']", "隐私政策"],
    ],
    title: {
      static: {
        "Welcome - Hugging Face": "欢迎 - Hugging Face",
        "Models - Hugging Face": "模型 - Hugging Face",
        "Datasets - Hugging Face": "数据集 - Hugging Face",
        "Spaces - Hugging Face": "应用空间 - Hugging Face",
        "Pricing - Hugging Face": "定价 - Hugging Face",
        "Organizations - Hugging Face": "组织 - Hugging Face",
        "Collections - Hugging Face": "收藏集 - Hugging Face",
        "Daily Papers - Hugging Face": "每日论文 - Hugging Face",
        "Hugging Face - Documentation": "Hugging Face - 文档",
        "Hugging Face - Learn": "Hugging Face - 学习",
      },
      regexp: [[/^(.+) - Hugging Face$/, "$1 - Hugging Face"]],
    },
  },

  welcome: {
    static: {
      "Welcome to Hugging Face": "欢迎来到 Hugging Face",
      "What are you interested in?": "你对什么感兴趣？",
      Explorer: "探索者",
      "App Builder": "应用构建者",
      Engineer: "工程师",
      Researcher: "研究者",
      "Explore models, datasets, papers and applications.": "探索模型、数据集、论文和应用。",
      "Build and share AI applications.": "构建并分享 AI 应用。",
      "Use open source libraries and production tools.": "使用开源库和生产工具。",
      "Discover research papers and state-of-the-art models.": "发现研究论文和前沿模型。",
      "Open source libraries": "开源库",
      "HF Spaces": "HF Spaces",
      HuggingChat: "HuggingChat",
      LeRobot: "LeRobot",
      "Train a model": "训练模型",
      "Local Models": "本地模型",
      "Inference Playground": "推理体验区",
      DeepSite: "DeepSite",
      "Data Studio": "数据工作室",
      "Dedicated Endpoints": "专用端点",
      Leaderboard: "排行榜",
      Smolagents: "Smolagents",
      "Get started with Hugging Face": "开始使用 Hugging Face",
      "Start exploring": "开始探索",
      "Start building": "开始构建",
      "View documentation": "查看文档",
      "Join the community": "加入社区",
      "What brings you to Hugging Face?": "你为什么来到 Hugging Face？",
      "Choose your main interest so we can personalize your experience.":
        "选择你的主要兴趣，我们会据此个性化你的体验。",
      "You can always change this later.": "之后你随时可以修改。",
      "Skip for now": "暂时跳过",
      "Continue to Hugging Face": "继续前往 Hugging Face",
      "Explore the Hub": "探索 Hub",
      "Build with Spaces": "使用 Spaces 构建",
      "Read the docs": "阅读文档",
      "Chat with HuggingChat": "使用 HuggingChat 聊天",
      "Find models for your task": "查找适合你任务的模型",
      "Discover datasets": "发现数据集",
      "Browse community apps": "浏览社区应用",
      "Follow trending papers": "关注热门论文",
      "Create your first Space": "创建你的第一个应用空间",
      "Use the Hub in production": "在生产环境使用 Hub",
      "Train and evaluate models": "训练和评估模型",
      "Deploy models": "部署模型",
      "Manage your profile": "管理你的个人资料",
    },
    selector: [
      ["a[href='/welcome']", "欢迎"],
      ["a[href='/docs/hub/index']", "Hub 文档"],
      ["a[href='/spaces']", "应用空间"],
      ["a[href='/chat']", "HuggingChat"],
    ],
    title: {
      static: {
        "Welcome - Hugging Face": "欢迎 - Hugging Face",
      },
    },
  },

  models: {
    selector: [["h1", "模型"]],
  },

  datasets: {
    selector: [["h1", "数据集"]],
  },

  spaces: {
    selector: [["h1", "应用空间"]],
  },

  docs: {
    static: {
      Documentation: "文档",
      "Search documentation": "搜索文档",
      "Search docs": "搜索文档",
      "Hugging Face Documentation": "Hugging Face 文档",
      "Hugging Face Hub documentation": "Hugging Face Hub 文档",
      "Getting Started": "开始使用",
      "Get Started": "开始使用",
      Quickstart: "快速开始",
      Installation: "安装",
      Tutorials: "教程",
      "How-to guides": "操作指南",
      "Conceptual guides": "概念指南",
      "API reference": "API 参考",
      "API Reference": "API 参考",
      Guides: "指南",
      Examples: "示例",
      Overview: "概览",
      "Model cards": "模型卡片",
      "Dataset cards": "数据集卡片",
      "Spaces Overview": "应用空间概览",
      "Hub API": "Hub API",
      "Hub client library": "Hub 客户端库",
      "Repository": "仓库",
      "Repositories": "仓库",
      "Files and versions": "文件和版本",
      "Pull requests": "拉取请求",
      "Discussions": "讨论",
      "Collections": "收藏集",
      "Inference Providers": "推理供应商",
      "Inference Endpoints": "推理端点",
      "Text Generation Inference": "文本生成推理",
      "Tokenizers": "分词器",
      "Transformers": "Transformers",
      "Diffusers": "Diffusers",
      "Datasets": "数据集",
      "Evaluate": "Evaluate",
      "Accelerate": "Accelerate",
      "PEFT": "PEFT",
      "TRL": "TRL",
      "Gradio": "Gradio",
      "Computer Vision": "计算机视觉",
      "Natural Language Processing": "自然语言处理",
      "Audio": "音频",
      "Tabular": "表格",
      "Reinforcement Learning": "强化学习",
      "Deploy": "部署",
      "Train": "训练",
      "Optimize": "优化",
      "Evaluate models": "评估模型",
      "Share models": "分享模型",
      "Share datasets": "分享数据集",
      "Create a Space": "创建应用空间",
      "Edit this page": "编辑此页面",
      "Open in Colab": "在 Colab 中打开",
      "Open in GitHub": "在 GitHub 中打开",
      "Copy page": "复制页面",
      "Copy code": "复制代码",
      "Copied!": "已复制！",
      "Previous": "上一篇",
      "Next": "下一篇",
      "On this page": "本页目录",
      "Table of contents": "目录",
      "Was this page helpful?": "这个页面有帮助吗？",
      "Yes": "是",
      "No": "否",
      "Sign up": "注册",
      "Sign in": "登录",
      "Create an account": "创建账号",
      "Using the Hub": "使用 Hub",
      "Upload files": "上传文件",
      "Download files": "下载文件",
      "Manage repositories": "管理仓库",
      "Access tokens": "访问令牌",
      "User access tokens": "用户访问令牌",
      "Authentication": "身份验证",
      "Environment variables": "环境变量",
      "Command Line Interface": "命令行界面",
      "Python library": "Python 库",
      "JavaScript library": "JavaScript 库",
    },
    regexp: [
      [/^(.+) documentation$/, "$1 文档"],
      [/^Using (.+)$/, "使用 $1"],
      [/^Getting started with (.+)$/, "$1 快速入门"],
    ],
    selector: [
      ["a[href='/docs']", "文档"],
      ["a[href='/docs/hub/index']", "Hub 文档"],
      ["a[href='/docs/transformers/index']", "Transformers 文档"],
      ["a[href='/docs/diffusers/index']", "Diffusers 文档"],
      ["a[href='/docs/datasets/index']", "Datasets 文档"],
      ["a[href='/docs/accelerate/index']", "Accelerate 文档"],
    ],
    title: {
      static: {
        "Hugging Face - Documentation": "Hugging Face - 文档",
      },
      regexp: [[/^(.+) documentation - Hugging Face$/, "$1 文档 - Hugging Face"]],
    },
  },

  learn: {
    static: {
      "Hugging Face Learn": "Hugging Face 学习",
      "Hugging Face Learning": "Hugging Face 学习",
      "Learn": "学习",
      "Courses": "课程",
      "LLM Course": "大语言模型课程",
      "Agents Course": "智能体课程",
      "Diffusion Course": "扩散模型课程",
      "Audio Course": "音频课程",
      "Computer Vision Course": "计算机视觉课程",
      "Deep Reinforcement Learning Course": "深度强化学习课程",
      "NLP Course": "自然语言处理课程",
      "Open-source AI cookbook": "开源 AI 实用手册",
      "Prerequisites": "前置要求",
      "Setup": "设置",
      "Authenticate": "身份验证",
      "Create a repository": "创建仓库",
      "Create a dataset repository": "创建数据集仓库",
      "Create a model repository": "创建模型仓库",
      "Upload files": "上传文件",
      "Download files": "下载文件",
      "Run inference": "运行推理",
      "Fine-tune a model": "微调模型",
      "Train a model": "训练模型",
      "Evaluate a model": "评估模型",
      "Share a model": "分享模型",
      "Share a dataset": "分享数据集",
      "Deploy a model": "部署模型",
      "Build a demo": "构建演示",
      "Build an app": "构建应用",
      "Use Spaces": "使用 Spaces",
      "Use datasets": "使用数据集",
      "Use transformers": "使用 Transformers",
      "Use diffusers": "使用 Diffusers",
      "Chapter": "章节",
      "Unit": "单元",
      "Lesson": "课程",
      "Start the course": "开始课程",
      "Continue learning": "继续学习",
      "Previous chapter": "上一章",
      "Next chapter": "下一章",
      "Take the quiz": "参加测验",
      "Check your answer": "检查答案",
      "Show solution": "显示答案",
      "Hide solution": "隐藏答案",
      "Community tutorials": "社区教程",
      "Tutorials": "教程",
      "Guides": "指南",
      "Examples": "示例",
      "Resources": "资源",
    },
    regexp: [
      [/^Chapter ([0-9]+)$/, "第 $1 章"],
      [/^Unit ([0-9]+)$/, "第 $1 单元"],
      [/^Lesson ([0-9]+)$/, "第 $1 课"],
      [/^(.+) Course$/, "$1 课程"],
    ],
    selector: [
      ["a[href='/learn']", "学习"],
      ["a[href='/learn/llm-course']", "大语言模型课程"],
      ["a[href='/learn/agents-course']", "智能体课程"],
      ["a[href='/learn/diffusion-course']", "扩散模型课程"],
    ],
    title: {
      static: {
        "Hugging Face - Learn": "Hugging Face - 学习",
      },
      regexp: [[/^(.+) Course - Hugging Face$/, "$1 课程 - Hugging Face"]],
    },
  },
};
